---
- hosts: all
  become_user: gregory
  become: yes
  tasks:
  
  ####################################
  # Creating a directory on the host #
  #####################################
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: ~/temp/nextcloud/
      state: directory
      mode: '0777'
      
  ###############################
  # Checkout the Nextcloud Repo #
  ###############################
  - name: Git Checkout Nextcloud
    ansible.builtin.git:
      repo: 'https://github.com/gregoryca/nextcloud.git'
      dest: ~/temp/nextcloud/

  ######################
  # Copy compose stack #
  ######################
  - name: Copy file with owner and permissions
    copy:
      src: ~/temp/nextcloud/
      dest: ~/srv/nextcloud/
      remote_src: yes
    
  #######################
  # deploy compose file #
  #######################
  - name: deploy Docker Compose stack on remote server
    docker_compose:
      project_src: ~/srv/nextcloud/
      files:
      - docker-compose.yml
      recreate: always

  #########################################
  # Clean up temp folder after deployment #
  #########################################
  - name: Delete content & directory
    file:
      state: absent
      path: ~/temp/