version: '3.3'

services:
  app:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: always
    volumes:
      - ./data/appdata:/config
      - /nextcloud-data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    networks:
      - web-secure

    labels:
       - "traefik.enable=true"

       # web interface
       - "traefik.http.routers.nextcloud-secure.rule=Host(`cloud.cloud-migrations.nl`)"
       - "traefik.http.routers.nextcloud-secure.tls.certresolver=production"
       - "traefik.http.routers.nextcloud-secure.tls=true"
       - "traefik.http.routers.nextcloud-secure.entrypoints=web-secure"

       - "traefik.http.services.nextcloud-secure.loadbalancer.server.port=80" #port to the webservice

networks:
  web-secure:
    external: true