services:
  nextcloud:
    deploy:
      resources:
        limits:
          memory: 6G
    image: nextcloud:32.0.2
    container_name: nextcloud
    restart: unless-stopped
    volumes:
      - /nextcloud-data/nextcloud-data:/var/www/html/data
      - ./nextcloud-app/:/var/www/html
      - ./nextcloud-log:/var/log/
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./opcache-recommed.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
      - ./geoip_db:/var/lib/GeoIP/
      - ./nextcloudworkers.conf:/etc/apache2/conf-enabled/nextcloudworkers.conf
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}
      - PHP_MEMORY_LIMIT=1024M
    networks:
      - web-secure
    ports:
      - 80:80
    links:
      - mariadb

  mariadb:
    container_name: nextcloud.mariadb
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - ./mysql-data/:/var/lib/mysql:rw
    ports:
      - 3306:3306
    networks:
      - web-secure

  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: nextcloud.phpmyadmin
     environment:
       PMA_HOST: ${MYSQL_HOST}
       PMA_PORT: 3306
       UPLOAD_LIMIT: 200000000
     restart: unless-stopped
     ports: 
      - 8080:80
     networks:
      - web-secure
     links:
      - mariadb
      
  redis:
    image: redis:latest
    container_name: nextcloud.redis
    hostname: redis
    networks:
      - web-secure
    command: "redis-server --save 60 1000"
    volumes:
      - ./redis-data:/data
    restart: unless-stopped
    environment:
      - REDIS_REPLICATION_MODE=master

  collabora:
    container_name: nextcloud.collabora
    image: collabora/code:25.04.7.3.1
    tty: true
    network_mode: host
    restart: unless-stopped
    environment:
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
      - username=gregory
      - domain=cloud

  # nextcloud-appapi-harp:
  #   environment:
  #     - HP_SHARED_KEY=${HP_SHARED_KEY}
  #     - NC_INSTANCE_URL=https://cloud.apex-migrations.net
  #     - HP_EXAPPS_ADDRESS=localhost:8780
  #   volumes:
  #       - /var/run/docker.sock:/var/run/docker.sock
  #       - /certs:/certs
  #   container_name: appapi-harp
  #   hostname: appapi-harp
  #   restart: unless-stopped
  #   networks:
  #     - web-secure
  #   ports:
  #     - 8780:8780
  #   image: ghcr.io/nextcloud/nextcloud-appapi-harp:release

networks:
  web-secure:
    external: true
