services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    hostname: nextcloud
    network_mode: host
    restart: unless-stopped
    volumes:
      - /nextcloud-data:/data
      - ./nextcloud-app/:/var/www/html
      - ./nextcloud-log:/var/log/
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./opcache-recommed.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}

  mariadb:
    container_name: nextcloud.mariadb
    image: mariadb:10.6
    hostname: db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - ./data/:/var/lib/mysql:rw

  cron:
    container_name: nextcloud.cronjobs
    image: nextcloud:apache
    hostname: cron
    restart: always
    volumes:
      - ./nextcloud-app/:/var/www/html:rw
      - /nextcloud-data:/data:rw
      - /usr/bin/python3/:/python3/
    entrypoint: /cron.sh
    network_mode: host

  redis:
    image: redis:latest
    container_name: nextcloud.redis
    hostname: redis
    network_mode: host
    command: "redis-server --save 60 1000"
    volumes:
      - ./redis-data:/data
    restart: unless-stopped
    environment:
      - REDIS_REPLICATION_MODE=master

  # collabora:
  #   container_name: nextcloud.collabora
  #   image: collabora/code:latest
  #   tty: true
  #   network_mode: host
  #   restart: unless-stopped

  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: nextcloud.phpmyadmin
     hostname: db
     environment:
       PMA_HOST: nextcloud
       PMA_PORT: 3306
       UPLOAD_LIMIT: 200000000
     restart: unless-stopped
     ports: 
      - 8080:80

  # nextcloud-appapi-dsp:
  #   environment:
  #       - NC_HAPROXY_PASSWORD=some_secure_password
  #   volumes:
  #       - /var/run/docker.sock:/var/run/docker.sock:ro
  #   container_name: nextcloud-appapi-dsp
  #   hostname: nextcloud-appapi-dsp
  #   restart: unless-stopped
  #   privileged: true
  #   image: ghcr.io/cloud-py-api/nextcloud-appapi-dsp:release
  #   network_mode: host

## to enter the nextcloud occ, use the following command:
# sudo docker exec -it --user www-data nextcloud.ui php occ


## To backup files use the following command:
# mysqldump --single-transaction -h 192.168.2.116 -u nextcloud -plaliloe nextcloud_db > nextcloud-sqlbkp_`date +"%Y%m%d"`.bak