services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud.ui
    hostname: nextcloud
    network_mode: host
    restart: unless-stopped
    volumes:
      - /nextcloud-data:/data
      - ./nextcloud-app/:/var/www/html
      - ./nextcloud-log:/var/log/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}

  mariadb:
    container_name: nextcloud.mariadb
    image: mariadb:10.8.3
    restart: always
    command: --skip-grant-tables
    network_mode: host
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      innodb_large_prefix: true
      innodb_file_format: barracuda
      innodb_file_per_table: 1
    volumes:
      - ./data/mariadb:/var/lib/mysql

  # nextcloud-appapi-dsp:
  #   environment:
  #       - NC_HAPROXY_PASSWORD=some_secure_password
  #   volumes:
  #       - /var/run/docker.sock:/var/run/docker.sock:ro
  #   container_name: nextcloud-appapi-dsp
  #   hostname: nextcloud-appapi-dsp
  #   restart: unless-stopped
  #   privileged: true
  #   image: ghcr.io/cloud-py-api/nextcloud-appapi-dsp:release
  #   network_mode: host

  cron:
    container_name: nextcloud.cronjobs
    image: nextcloud:apache
    restart: always
    volumes:
      - ./nextcloud-app/:/var/www/html:rw
      - /nextcloud-data:/data:rw
      - /usr/bin/python3/:/python3/
    entrypoint: /cron.sh
    network_mode: host

#   phpmyadmin:
#      image: phpmyadmin/phpmyadmin
#      container_name: nextcloud.phpmyadmin
# #    network_mode: host
#      environment:
#        PMA_HOST: ${PMA_HOST}
#        PMA_PORT: ${PMA_PORT}
#        UPLOAD_LIMIT: 200000000
#      restart: unless-stopped

  redis:
    image: redis:latest
    container_name: nextcloud.redis
    hostname: nextcloud.redis
    network_mode: host
    command: "redis-server --requirepass ${REDIS_HOST_PASSWORD}"
    volumes:
      - ./redis-data:/data
    restart: unless-stopped
    environment:
      - REDIS_REPLICATION_MODE=master

  collabora:
    container_name: nextcloud.collabora
    image: collabora/code:latest
    tty: true
    network_mode: host
    restart: unless-stopped


## to enter the nextcloud occ, use the following command:
# sudo docker exec -it --user www-data nextcloud.ui php occ
