<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'datadirectory' => '/data',
  'instanceid' => 'oc32w4sps346',
  'passwordsalt' => 'tSPOWQDj6Z5fxcEQh1ykCJ9C7b55ud',
  'secret' => 'UBYgVYhqP4SPk5vs4oim5kTouH7zKo5fEEZ6clLv+Q1nnFy0',
  'trusted_domains' => 
  array (
    0 => 'cloud.cloud-migrations.nl',
  ),
  'dbtype' => 'mysql',
  'version' => '24.0.3.2',
  'overwrite.cli.url' => 'https://cloud.cloud-migrations.nl',
  'dbname' => 'nextcloud_db',
  'dbhost' => 'mariadb',
  'dbport' => '5432',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'oc_a-grcr',
  'dbpassword' => '5HAfsfSiYnZWjOzWwc0jiBjTSlIukk',
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'has_rebuilt_cache' => true,
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'cloud-migrations.nl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'mail.mijndomein.nl',
  'mail_smtpport' => '465',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'cloud@cloud-migrations.nl',
  'mail_smtppassword' => 'Laliloe4life#',
);
